### ISSUE TITLE
Bug - Label - 'Add label' does not match core

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#11975]
The 'Add label' in the [editable-label-group-with-add-button example](https://www.patternfly.org/components/label#editable-label-group-with-add-button) in the react documentation doesn't have a pointer cursor on hover and is not a button under the hood like the [Add label example](https://www.patternfly.org/components/label/html#add-label) in the core documentation.

**Comment by enricobguedes** [comment]
I believe this has been fixed, I am not able to reproduce the reported issue. 

Using the provided links and searching for the mentioned buttons, they are both of type "button" and display the correct cursor. (IE. clickable).

@nicolethoen can you revalidate?

**Comment by nicolethoen** [comment]
the 'add label' button for me in the example linked react docs is still showing the incorrect cursor and does not look like its hovering over a button
