### ISSUE TITLE
PF4 Dropdown appears behind tabs

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1636]
The PF4 dropdown appears behind the PF4 tabs component, when expanded. This does not appear to happen elsewhere.

<img width="1494" alt="Screen Shot 2019-03-22 at 7 00 42 PM" src="https://user-images.githubusercontent.com/17481322/54857322-1d032080-4cd5-11e9-96ca-6376396fe28a.png">

**Comment by dtaylor113** [comment]
> This does not appear to happen elsewhere.

@dlabrecq, meaning elsewhere in your application or elsewhere in PF4 Docs?

**Comment by dlabrecq** [comment]
It looks ok when overlaying other components in my app. It appears to be an issue with the tabs component only.

**Comment by tlabaj** [comment]
@mcoker does change in css have to be made for this issue?

**Comment by boaz0** [comment]
@tlabaj looking at the css of `tab` the `z-index` attribute of the button is set to `300` (var(--pf-global--ZIndex--md)) while `--pf-c-dropdown__menu--ZIndex` is set to 100 (var(--pf-global--ZIndex-xs)).

I believe setting `--pf-c-dropdown__menu--ZIndex` to 300 fixes it.

**Comment by dlabrecq** [comment]
This is still an issue for Cost Management

**Comment by tlabaj** [comment]
@dlaThis this should be resolved in the latest version of react-core.  Can you verify it works for you so we can close this issue.

**Comment by dlabrecq** [comment]
It looks ok with the latest packages

**Comment by dlabrecq** [comment]
This is still a problem with the latest packages. New screenshot below

![Screen Shot 2019-09-11 at 1 08 30 PM](https://user-images.githubusercontent.com/17481322/64735036-be657500-d4b5-11e9-9a80-872c1c7f90dc.png)

**Comment by dlabrecq** [comment]
![chrome-capture](https://user-images.githubusercontent.com/17481322/64737033-f2429980-d4b9-11e9-874b-a5be462c89f3.gif)

**Comment by dlabrecq** [comment]
It appears that Insights Chrome is including the latest version (i.e., "^2.33.5") for the patternfly base CSS. 

See https://github.com/RedHatInsights/insights-chrome/blob/master/package.json#L111

<img width="988" alt="Screen Shot 2019-09-27 at 3 10 56 PM" src="https://user-images.githubusercontent.com/17481322/65795854-3cbe4a00-e139-11e9-9969-15d82a4a8348.png">

**Comment by mcoker** [comment]
The last time I looked at this, it was due to an older version of core being included alongside the new version. Is there an environment where I can reproduce this bug? I put together a demo and am unable to reproduce it - https://codepen.io/mcoker/pen/qBWGEWw

**Comment by dlabrecq** [comment]
Please see the issue here https://ci.cloud.redhat.com/beta/hybrid/cost-management/aws. I've provided the login creds offline.

**Comment by dlabrecq** [comment]
Insights includes the PatternFly base CSS, while Cost Management only includes the PatternFly addons. See https://github.com/project-koku/koku-ui/blob/master/webpack.config.js#L53

I'm certain we're using the latest, so there shouldn't any old CSS? What old selector should I be looking for?

You can find the issue here https://ci.cloud.redhat.com/beta/hybrid/cost-management/aws. Please use the login creds I provided offline.

**Comment by mcoker** [comment]
This `z-index` declaration is the offending style. It no longer exists in patternfly.

<img width="2076" alt="Screen Shot 2019-09-27 at 6 13 36 PM" src="https://user-images.githubusercontent.com/35148959/65807258-1b6a5780-e153-11e9-97bf-0f00b55ee0ec.png">
![Untitled 3](https://user-images.githubusercontent.com/35148959/65807257-1b6a5780-e153-11e9-8b10-e122cb34317d.png)

**Comment by dlabrecq** [comment]
I believe this is due to the components embedding their own CSS. 

The Insights components package appears to be using an older version of PatternFly, while Cost Management is using the latest PatternFly React components. As a result, there are duplicated CSS blocks and stylesheets.

That said, that Insights components package has been deprecated. The new package includes the latest PatternFly, so we can use that instead.

This suggests that component CSS can easily get out of sync. If that particular package is not kept in sync, we're likely to have trouble again.
