### ISSUE TITLE
Alert has hard-coded title for screen reader

### ISSUE THREAD

**Issue by ssilvert** [patternfly/patternfly-react#2023]
Alerts should not have a hard-coded, unlocalizable title.   It looks like this was addressed in https://github.com/patternfly/patternfly-react/issues/601, but now the problem is back?

Now we have:
```javascript
  variantLabel = variantLabel || capitalize(AlertVariant[variant]);
  const readerTitle = (
    <React.Fragment>
      <span className={css(accessibleStyles.screenReader)}>{`${variantLabel} alert:`}</span>
      {title}
    </React.Fragment>
  );```

**Comment by redallen** [comment]
Please check if the logic in #1978 solves your problem. Here's the file:
```
export const AlertActionCloseButton = ({
  className = '',
  onClose = () => undefined as any,
  'aria-label': ariaLabel = '',
  title,
  variantLabel = '',
  ...props
}: AlertActionCloseButtonProps) => (
  <Button
    variant={ButtonVariant.plain}
    onClick={onClose}
    aria-label={ariaLabel === '' ? `Close ${variantLabel} alert: ${title}` : ariaLabel}
    {...props}
  >
    <TimesIcon />
  </Button>
);
```

**Comment by ssilvert** [comment]
From reading the code, it looks like there is still the hard-coded {`${variantLabel} alert:`}.  That should not be there.

I don't want my alert to say "Success alert:"

**Comment by tlabaj** [comment]
@zach can you please fix this as part of your Pr you already have up.

**Comment by redallen** [comment]
@ssilvert I just updated my PR to use:
```
<span className={css(accessibleStyles.screenReader)}>
        {variantLabel ? variantLabel : `${capitalize(variant)} alert:`}
</span>
```

**Comment by ssilvert** [comment]
IMO, this is still wrong.  Under no circumstances should the Alert have an unlocalizable, hard-coded message.  Just take the message passed in and display it.  

It's not just for screen reader.  It's for everything.  No hard-coded messages should ever be displayed to the user.

**Comment by redallen** [comment]
With the new logic, we do take the message passed in (`variantLabel`) and display it. The old logic was wrong. We just set defaults for those who don't set a `variantLabel` or `aria-label`.

**Comment by ssilvert** [comment]
I don't want a variantLabel to be displayed.  And I certainly don't want an unlocalized, hard-coded one to be displayed.

I just want to pass in a message and have it displayed exactly as I specified.

BTW, the documentation for these properties do not show up here https://patternfly-react.surge.sh/patternfly-4/components/alert/

**Comment by redallen** [comment]
The PR that is out will have the exact string you pass it displayed. It will also fix the documentation: https://1978-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/alert/

If you don't want default `aria-label` or `variantLabel`s displayed that have hard-coded text, you can pass an empty string to override the default behavior. If you want to make the argument that defaults should not exist by default, open a separate issue that applies to all components.

**Comment by ssilvert** [comment]
I think that a developer expects to just pass in a message and have that message displayed as-is without modification.  Without the docs, it was even more confusing as I didn't know the variantLabel param even existed.

As long as the docs tell you how to disable the default behavior, it should be ok.  I would add that to the description of the variantLabel and aria-label props.
