### ISSUE TITLE
Bug - [Select] - [Clicking on footer closes Select dropdown]

### ISSUE THREAD

**Issue by jelly** [patternfly/patternfly-react#6983]
**Describe the problem**

Between @patternfly/react-core@4.198.5 and @patternfly/react-core@4.192.15 the issue occurs where clicking on an element/button in the footer closes the dropdown dialog. Before this did not happen, what is noticed is that `onToggle` is triggered and not the `ToggleGroupItem`'s event handler. 

**How do you reproduce the problem?**

```
          <Select
          isGrouped
           variant={SelectVariant.typeahead}
           menuAppendTo={() => document.body}
            aria-label="Select Input"
            onToggle={this.onToggle}
            onSelect={this.onSelect}
            selections={selected}
            isOpen={isOpen}
            isInputValuePersisted
            onTypeaheadInputChanged={value => console.log(value)}
            footer={<ToggleGroup>
                  <ToggleGroupItem text="test" onClick={() => console.log("test")}/>
                  <ToggleGroupItem text="next" onClick={() => console.log("test")}/>
            </ToggleGroup>
      }
       >
            {this.options}
          </Select>
```

**Expected behavior**

Clicking on the footer does not close the Select dropdown.

**Is this issue blocking you?**

Blocks updating to a new PF4: https://github.com/cockpit-project/cockpit-podman/pull/931

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**
 - OS: Fedora
 - Browser: Chrome
 - Version 98

**Comment by nicolethoen** [comment]
@tlabaj was it possible this was already addressed with some of the most recent fixes for Select? It just has not been released yet?

**Comment by jelly** [comment]
I've uploaded my reproducer as example here https://github.com/jelly/patternfly-react/commit/dcf4b269fdee1a6832cce05835f3561d9b6c8136 and can still reproduce it with the latest `main` 5b472303da22cb9c67e9977b3933f6576c27ac01
